begin;
insert into ops.migration_entity_map(entity_key,source_sheet,target_schema,target_table,source_pk_header,target_pk_column,source_of_truth,migration_priority,sensitivity,id_regex,compare_fields,target_ready,notes)
values
('Evidence','13_เอกสาร_Evidence','docs','evidence','Evidence ID','evidence_id','Data Hub + Vault','P0','PRIVATE','^WC-EV-[0-9]{6}$',array['evidence_id','file_id','evidence_type','evidence_class','evidence_date','verification_status','source_authority'],true,'File relation is reconciled separately from URL text.'),
('Consent','14_Consent_PDPA','privacy','consents','Consent ID','consent_id','Data Hub + Consent Evidence',null,'PRIVATE','^WC-CN-[0-9]{6}$',array['consent_id','candidate_id','purpose_code','decision','effective_at','evidence_id'],true,null),
('Raw Input','19_Raw_Input_Log','ops','raw_inputs','Raw Input ID','raw_input_id','Data Hub + Original Source','P0','PRIVATE','^WC-RAW-[0-9]{6}$',array['raw_input_id','source_system','channel','original_ref','processing_status'],true,null),
('File Registry','20_File_Registry','docs','files','File Registry ID','file_id','Data Hub + Drive','P0','PRIVATE','^WC-FILE-[0-9]{6}$',array['file_id','raw_input_id','provider','provider_file_ref','legacy_drive_file_id','source_url','original_filename','stored_filename','mime_type','size_bytes','checksum_sha256','visibility','sensitivity','storage_status'],true,null),
('Data_Quality','21_Data_Quality_Queue','ops','data_quality_issues','DQ Issue ID','dq_issue_id','Data Hub',null,'INTERNAL','^WC-DQ-[0-9]{6}$',array['dq_issue_id','entity_type','entity_id','field_name','issue_type','current_value','incoming_value','raw_input_id','severity','status'],true,null)
on conflict(entity_key) do update set source_sheet=excluded.source_sheet,target_schema=excluded.target_schema,target_table=excluded.target_table,source_pk_header=excluded.source_pk_header,target_pk_column=excluded.target_pk_column,source_of_truth=excluded.source_of_truth,migration_priority=excluded.migration_priority,sensitivity=excluded.sensitivity,id_regex=excluded.id_regex,compare_fields=excluded.compare_fields,target_ready=excluded.target_ready,notes=excluded.notes,updated_at=now();
commit;