insert into analytics.kpi_catalog(kpi_id,domain,kpi_name,kpi_class,definition,numerator,denominator,time_grain,primary_source,required_fields,eligibility_filter,result_type,not_ready_rule,owner_role,dashboard,priority)
values
('KPI-CAN-001','Candidate','New Leads','SNAPSHOT/EVENT','Candidate leads received in selected period','Count candidate.lead.received / candidate created events',null,'DAY/WEEK/MONTH','ops.events + core.candidates','event_type, occurred_at, candidate_id','Unique logical candidate/event','COUNT','If event history unavailable, show current LEAD count separately as Snapshot','Candidate Ops','Founder Daily','P0'),
('KPI-CAN-002','Candidate','Qualified Leads','EVENT','Unique candidates that reached QUALIFIED in selected period','Distinct candidate_id with transition to QUALIFIED',null,'DAY/WEEK/MONTH','ops.activities/events','candidate_id, from_status, to_status, occurred_at','First qualifying transition per candidate/period','COUNT','Do not infer from current status for historical period','Candidate Ops','Founder Weekly','P0'),
('KPI-CAN-003','Candidate','Lead→Qualified Rate','FUNNEL','Share of eligible leads that reached QUALIFIED','Qualified cohort leads','Lead cohort','WEEK/MONTH/COHORT','analytics candidate_stage fact','lead_at, qualified_at','Lead cohort with adequate observation window','PERCENT','NOT READY if stage history/denominator incomplete','Data Audit','Founder Weekly','P0'),
('KPI-CAN-004','Candidate','Appointment Rate','FUNNEL','Share of qualified candidates receiving appointment','Qualified candidates with appointment','Eligible qualified cohort','WEEK/MONTH/COHORT','placements + stage history','candidate_id, appointment_at, qualified_at','Qualified cohort; dedupe candidate/job policy','PERCENT','NOT READY if qualification history missing','Candidate Ops','Founder Weekly','P0'),
('KPI-CAN-005','Candidate','Show Rate','FUNNEL','Share of occurred appointments where candidate showed','Appointments with show/applied/interview outcome','Appointments that occurred','WEEK/MONTH','placements','appointment_at, status/outcome','appointment_at <= as_of; exclude cancelled-before-appointment','PERCENT','NOT READY if appointment outcome not standardized','Candidate Ops','Founder Weekly','P0'),
('KPI-CAN-006','Candidate','No-show Rate','FUNNEL','Share of occurred appointments resulting NO_SHOW','NO_SHOW appointments','Appointments that occurred','WEEK/MONTH','placements','appointment_at, placement_status','appointment_at <= as_of','PERCENT','NOT READY if appointment/outcome missing; never use D30/Qualified','Candidate Ops','Founder Daily','P0'),
('KPI-CAN-007','Placement','Starts','EVENT','Placements with verified start date in selected period','Count placements started',null,'DAY/WEEK/MONTH','placements + evidence','placement_id, start_date','start_date in period; valid placement','COUNT','NOT READY if start date unverified for important reporting','Candidate Ops','Founder Daily','P0'),
('KPI-RET-001','Retention','D7 Retention','COHORT','Share of D7-eligible starts confirmed active at D7','D7 positive outcomes','Starts with start_date <= as_of-7d','COHORT/WEEK/MONTH','placements/followups','start_date, D7 outcome','Only eligible starts; explicit positive D7 outcome','PERCENT','NOT READY until milestone outcome vocabulary is standardized','Candidate Ops','Founder Weekly','P0'),
('KPI-RET-002','Retention','D30 Retention','COHORT','Share of D30-eligible starts confirmed active at D30','D30 positive outcomes','Starts with start_date <= as_of-30d','COHORT/MONTH','placements/followups','start_date, D30 outcome','Only eligible starts; explicit positive D30 outcome','PERCENT','NOT READY until D30 outcomes exist; never D7/Appointed','Candidate Ops','Founder Weekly','P0'),
('KPI-RET-003','Retention','D90 Retention','COHORT','Share of D90-eligible starts active at D90','D90 positive outcomes','Starts with start_date <= as_of-90d','COHORT/MONTH','placements/followups','start_date, D90 outcome','Eligible starts only','PERCENT','NOT READY if cohort immature','Candidate Ops','Founder Monthly','P1'),
('KPI-CLI-001','Client','Active Clients','SNAPSHOT','Clients currently in ACTIVE CRM state','Count active clients',null,'AS-OF','clients','crm_status','crm_status=ACTIVE','COUNT','0 is valid only if client master complete','Client Sales','Founder Daily','P0'),
('KPI-CLI-002','Client','Open Job Demand','SNAPSHOT','Active jobs currently requiring candidates','Count active/open jobs',null,'AS-OF','jobs','job_status','ACTIVE and not closed','COUNT','Show data-quality badge if demand/headcount missing','Client Sales','Founder Daily','P0'),
('KPI-CLI-003','Client','Open Headcount','SNAPSHOT','Remaining requested headcount on active jobs','Requested headcount - verified fills','n/a','AS-OF','jobs + placements','job headcount, active starts/fills','Per active job; clamp at zero only if business rule confirmed','COUNT','NOT READY per job if headcount missing','Client Sales','Founder Daily','P0'),
('KPI-CLI-004','Client','Fill Rate','COHORT/PERIOD','Verified starts divided by confirmed demand for selected job cohort','Verified filled headcount','Confirmed requested headcount','WEEK/MONTH/JOB','jobs + placements','headcount, client_confirmed, start_date','Confirmed demand only','PERCENT','NOT READY if requested headcount not confirmed','Client Sales','Founder Weekly','P1'),
('KPI-CLI-005','Client','Time to Fill','DURATION','Median time from confirmed demand to verified start','Median(start - demand_confirmed_at)',null,'MONTH/JOB','jobs/events + placements','confirmed_at,start_date','Filled placements only','DAYS','NOT READY without demand confirmation timestamp','Client Sales','Founder Monthly','P1'),
('KPI-PAR-001','Partner','Partner Leads','EVENT','Unique candidate leads attributed to partner','Distinct attributed candidate leads',null,'WEEK/MONTH','raw/events + attribution','candidate_id, source_partner_id, attribution evidence','Approved attribution only','COUNT','Do not attribute merely because partner answered chat','Client Sales/Data Audit','Partner Weekly','P1'),
('KPI-PAR-002','Partner','Partner Starts','EVENT','Verified starts sourced to partner','Distinct started placements',null,'WEEK/MONTH','placements + candidate attribution','placement_id, partner_id,start_date','Approved source partner','COUNT','NOT READY if attribution unresolved','Client Sales','Partner Weekly','P1'),
('KPI-PAR-003','Partner','Partner Start Conversion','FUNNEL','Partner-sourced leads that became starts','Partner starts','Partner sourced lead cohort','MONTH/COHORT','analytics partner funnel','source_partner_id, lead_at,start_date','Approved attribution + observation window','PERCENT','NOT READY if lead attribution/history incomplete','Data Audit','Partner Weekly','P1'),
('KPI-PAR-004','Partner','Data Completeness','QUALITY','Required-stage fields present for partner leads','Complete partner-sourced records','Partner-sourced records','AS-OF/WEEK','candidate master + governance','required-stage fields','By current candidate stage','PERCENT','Show missing-field count with rate','Data Audit','Partner Weekly','P1'),
('KPI-FIN-001','Finance','Expected Revenue','SNAPSHOT','Revenue expected but not yet earned/collected','Sum expected amount',null,'AS-OF','finance.revenue / current Revenue sheet','gross/expected amount,status','status=EXPECTED','MONEY','NOT READY if amount inferred/unverified','Finance','Founder Daily','P0'),
('KPI-FIN-002','Finance','Earned Revenue','SNAPSHOT','Revenue that reached contractual earning milestone','Sum earned amount',null,'AS-OF','finance.revenue','amount,status,evidence','status=EARNED or later, per contract','MONEY','NOT READY if milestone/evidence unclear','Finance','Founder Daily','P0'),
('KPI-FIN-003','Finance','Invoiced Revenue','SNAPSHOT','Amount invoiced and not cancelled','Sum invoice gross/net per chosen semantic',null,'AS-OF/PERIOD','finance.revenue + AR','invoice,status','Valid invoice records','MONEY','NOT READY if invoice semantics inconsistent','Finance','Founder Daily','P0'),
('KPI-FIN-004','Finance','Collected Revenue','CASH','Cash actually received and matched','Sum verified net received',null,'DAY/WEEK/MONTH','revenue + bank/evidence','collection_date,net_received,payment_ref,evidence','Status COLLECTED with reliable payment match','MONEY','Never count chat promise as collected','Finance','Founder Daily','P0'),
('KPI-FIN-005','Finance','Client Outstanding','AR','Open collectible receivables','Sum outstanding AR',null,'AS-OF','accounts_receivable','gross/paid/outstanding,status,due_date','Open/overdue AR','MONEY','NOT READY if AR not initialized/reconciled','Finance','Founder Daily','P0'),
('KPI-FIN-006','Finance','Commission Payable','AP','Partner commissions eligible and awaiting payment','Sum commission amount',null,'AS-OF','commissions','state,amount','state=PAYABLE','MONEY','PAYABLE != PAID','Finance','Founder Daily','P0'),
('KPI-FIN-007','Finance','Contribution Margin','PROFITABILITY','Collected/earned revenue less direct attributable costs and commission using approved basis','Revenue basis - direct costs - commission basis',null,'MONTH/PLACEMENT','finance + accounting','revenue,cost,commission','Use one approved basis per report','MONEY/PERCENT','NOT READY if revenue basis mixed','Finance','Founder Monthly','P1'),
('KPI-FIN-008','Finance','Cash Balance','CASH','Reconciled business cash/bank balance','Closing reconciled balance',null,'AS-OF','bank/cash ledger','bank txn/reconciliation','Reconciled accounts only','MONEY','Manual Founder input can be clearly labeled estimated until bank integration','Finance','Founder Daily','P0'),
('KPI-DQ-001','Data Quality','Open Critical DQ','QUALITY','Open high/critical data quality issues','Count open critical/high DQ',null,'AS-OF','data_quality_issues','severity,status','OPEN/IN_REVIEW severe issues','COUNT','0 valid only if DQ process active','Data Audit','Founder Daily','P0'),
('KPI-DQ-002','Data Quality','Unprocessed Raw Input','QUALITY','Material raw inputs not completed/reviewed','Count backlog',null,'AS-OF','raw_inputs/events','processing_status,received_at','Exclude known non-material no-op','COUNT','Show oldest-age alongside count','Data Audit','Founder Daily','P0'),
('KPI-OPS-001','Operations','Follow-up Due','ACTION','Follow-ups due now/overdue','Count due follow-up tasks',null,'DAY/AS-OF','followups','next_followup,due,status','due<=as_of and not completed','COUNT','NOT READY if due date missing','Candidate Ops','Founder Daily','P0'),
('KPI-OPS-002','Operations','Automation Dead Letter','ACTION','Automation events exhausted/reviewable','Count DLQ events',null,'AS-OF','ops.dead_letters/events','state,event_type','DEAD_LETTER','COUNT','Any finance DLQ elevated severity','Automation','Founder Daily','P1')
on conflict (kpi_id) do update set domain=excluded.domain,kpi_name=excluded.kpi_name,kpi_class=excluded.kpi_class,definition=excluded.definition,numerator=excluded.numerator,denominator=excluded.denominator,time_grain=excluded.time_grain,primary_source=excluded.primary_source,required_fields=excluded.required_fields,eligibility_filter=excluded.eligibility_filter,result_type=excluded.result_type,not_ready_rule=excluded.not_ready_rule,owner_role=excluded.owner_role,dashboard=excluded.dashboard,priority=excluded.priority,updated_at=now();

insert into analytics.semantic_rules(rule_id,rule_name,required_behavior,example)
values
('SEM-001','0 ≠ NOT READY','If denominator/source is incomplete, return NOT_READY/null plus reason, not 0%','D30 retention before any D30-eligible cohort'),
('SEM-002','Current Status ≠ Historical Funnel','Historical conversion must use transition/event timestamps','Current STARTED candidate should still count as historical LEAD cohort'),
('SEM-003','Cohort Eligibility','Retention denominator includes only records old enough to reach milestone','D30 denominator: verified start_date <= as_of-30d'),
('SEM-004','One KPI one definition','KPI ID has one canonical numerator/denominator/time grain','No duplicate Collected with different cash basis'),
('SEM-005','Finance evidence-backed','Official finance KPI comes from reconciled operational/accounting records','COLLECTED requires payment evidence/match'),
('SEM-006','Attribution evidence-backed','Partner/source KPI uses approved attribution evidence','Partner replying in thread is not attribution'),
('SEM-007','Late-arriving facts','Recompute affected historical period/cohort when stronger source arrives','Backfilled start confirmation updates start cohort'),
('SEM-008','Timezone','Business reporting timezone Asia/Bangkok','Daily bucket closes at Bangkok local date'),
('SEM-009','Data freshness visible','Dashboard displays freshness/as-of and quality badge','As of 2026-08-29 23:30 ICT'),
('SEM-010','Drill-through','KPI should resolve to underlying Entity IDs/evidence where authorized','Collected amount → revenue/payment/evidence records')
on conflict (rule_id) do update set rule_name=excluded.rule_name,required_behavior=excluded.required_behavior,example=excluded.example;

insert into analytics.dq_gate_catalog(gate_id,kpi_domain,check_description,severity_if_fail,behavior_if_fail,owner_role,architecture_status)
values
('DQG-001','Funnel','Stage-transition history exists for selected period','HIGH','Rate = NOT_READY; snapshot counts may still show','Data Audit','PLANNED'),
('DQG-002','Appointment/No-show','Appointment date and standardized outcome present','HIGH','Show count quality warning / block rate','Candidate Ops','PLANNED'),
('DQG-003','Retention','Start date + milestone outcome + cohort eligibility available','HIGH','Retention = NOT_READY','Candidate Ops','PLANNED'),
('DQG-004','Finance Collected','Reliable payment evidence and match exist','CRITICAL','Exclude from official Collected','Finance','ACTIVE RULE'),
('DQG-005','Partner KPI','Attribution evidence resolved','HIGH','Exclude unresolved from partner performance; show unresolved count','Data Audit','ACTIVE RULE'),
('DQG-006','Client Fill','Confirmed requested headcount exists','HIGH','Fill Rate = NOT_READY for job/client period','Client Sales','PLANNED'),
('DQG-007','Accounting','Posted journal batches balanced','CRITICAL','Accounting dashboard red/blocked','Finance','ACTIVE RULE'),
('DQG-008','Freshness','Source/mart refreshed within required window','MEDIUM/HIGH','Show STALE badge; alerts if critical','Data Audit','PLANNED'),
('DQG-009','Files','Evidence File Registry link/object/source status valid','HIGH','Evidence-based KPI flagged','Data Audit','PLANNED'),
('DQG-010','Privacy','Dashboard role authorized for fields displayed','CRITICAL','Deny query/render','Architect/Data Audit','PLANNED')
on conflict (gate_id) do update set kpi_domain=excluded.kpi_domain,check_description=excluded.check_description,severity_if_fail=excluded.severity_if_fail,behavior_if_fail=excluded.behavior_if_fail,owner_role=excluded.owner_role,architecture_status=excluded.architecture_status,updated_at=now();

insert into analytics.acceptance_catalog(test_id,scenario,expected_behavior,critical)
values
('AN-001','No D30-eligible placements','D30 Retention returns NOT_READY/no eligible cohort, not 0%',true),
('AN-002','Candidate progressed LEAD→STARTED','Historical Lead cohort retains candidate even if current status STARTED',true),
('AN-003','Appointment NO_SHOW','No-show numerator increments and denominator is occurred appointment cohort',true),
('AN-004','Ambiguous appointment outcome','No-show/show rate blocked or quality flagged',true),
('AN-005','Chat says client paid but no evidence','Collected Revenue unchanged',true),
('AN-006','Payment evidence matched','Collected KPI reconciles to Revenue/Bank/AR evidence',true),
('AN-007','Partner responded but attribution absent','Partner KPI does not claim lead',true),
('AN-008','Dashboard role Content Studio','Candidate PII/Finance not exposed',true),
('AN-009','Source refresh stale','Dashboard shows STALE/as-of badge',true),
('AN-010','Founder KPI drill-through','KPI resolves to underlying entity/evidence IDs',true),
('AN-011','Heavy weekly query becomes slow','Materialization only introduced after measured need; semantic result unchanged',false),
('AN-012','Accounting month close','P&L/Trial Balance derived from journal and labeled provisional/closed',true)
on conflict (test_id) do update set scenario=excluded.scenario,expected_behavior=excluded.expected_behavior,critical=excluded.critical,updated_at=now();