begin;
create index if not exists ap_file_idx on finance.accounts_payable(file_id);
create index if not exists ap_placement_idx on finance.accounts_payable(placement_id);
create index if not exists ar_file_idx on finance.accounts_receivable(file_id);
create index if not exists ar_placement_idx on finance.accounts_receivable(placement_id);
create index if not exists bank_txn_client_idx on finance.bank_transactions(client_id);
create index if not exists bank_txn_expense_idx on finance.bank_transactions(expense_id);
create index if not exists bank_txn_file_idx on finance.bank_transactions(file_id);
create index if not exists bank_txn_partner_idx on finance.bank_transactions(partner_id);
create index if not exists bank_txn_placement_idx on finance.bank_transactions(placement_id);
create index if not exists bank_txn_raw_idx on finance.bank_transactions(raw_input_id);
create index if not exists commissions_override_partner_idx on finance.commissions(override_from_partner_id);
create index if not exists expenses_raw_idx on finance.expenses(source_raw_input_id);
create index if not exists journal_batches_candidate_idx on finance.journal_batches(candidate_id);
create index if not exists journal_batches_client_idx on finance.journal_batches(client_id);
create index if not exists journal_batches_file_idx on finance.journal_batches(file_id);
create index if not exists journal_batches_partner_idx on finance.journal_batches(partner_id);
create index if not exists journal_batches_placement_idx on finance.journal_batches(placement_id);
create index if not exists journal_batches_raw_idx on finance.journal_batches(raw_input_id);
create index if not exists monthly_close_evidence_idx on finance.monthly_close_checks(evidence_id);
create index if not exists revenue_raw_idx on finance.revenue(source_raw_input_id);
create index if not exists tax_documents_file_idx on finance.tax_documents(file_id);
commit;